# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flwr/proto/driver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from flwr.proto import task_pb2 as flwr_dot_proto_dot_task__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x66lwr/proto/driver.proto\x12\nflwr.proto\x1a\x15\x66lwr/proto/task.proto\"\x13\n\x11GetClientsRequest\"\x14\n\x12GetClientsResponse\"4\n\x12\x43reateTasksRequest\x12\x1e\n\x04task\x18\x01 \x03(\x0b\x32\x10.flwr.proto.Task\"\'\n\x13\x43reateTasksResponse\x12\x10\n\x08task_ids\x18\x01 \x03(\t\"9\n\x11GetResultsRequest\x12$\n\x08task_ids\x18\x01 \x03(\x0b\x32\x12.flwr.proto.Result\"9\n\x12GetResultsResponse\x12#\n\x07results\x18\x01 \x03(\x0b\x32\x12.flwr.proto.Result2\xf8\x01\n\x06\x44river\x12M\n\nGetClients\x12\x1d.flwr.proto.GetClientsRequest\x1a\x1e.flwr.proto.GetClientsResponse\"\x00\x12P\n\x0b\x43reateTasks\x12\x1e.flwr.proto.CreateTasksRequest\x1a\x1f.flwr.proto.CreateTasksResponse\"\x00\x12M\n\nGetResults\x12\x1d.flwr.proto.GetResultsRequest\x1a\x1e.flwr.proto.GetResultsResponse\"\x00\x62\x06proto3')



_GETCLIENTSREQUEST = DESCRIPTOR.message_types_by_name['GetClientsRequest']
_GETCLIENTSRESPONSE = DESCRIPTOR.message_types_by_name['GetClientsResponse']
_CREATETASKSREQUEST = DESCRIPTOR.message_types_by_name['CreateTasksRequest']
_CREATETASKSRESPONSE = DESCRIPTOR.message_types_by_name['CreateTasksResponse']
_GETRESULTSREQUEST = DESCRIPTOR.message_types_by_name['GetResultsRequest']
_GETRESULTSRESPONSE = DESCRIPTOR.message_types_by_name['GetResultsResponse']
GetClientsRequest = _reflection.GeneratedProtocolMessageType('GetClientsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCLIENTSREQUEST,
  '__module__' : 'flwr.proto.driver_pb2'
  # @@protoc_insertion_point(class_scope:flwr.proto.GetClientsRequest)
  })
_sym_db.RegisterMessage(GetClientsRequest)

GetClientsResponse = _reflection.GeneratedProtocolMessageType('GetClientsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETCLIENTSRESPONSE,
  '__module__' : 'flwr.proto.driver_pb2'
  # @@protoc_insertion_point(class_scope:flwr.proto.GetClientsResponse)
  })
_sym_db.RegisterMessage(GetClientsResponse)

CreateTasksRequest = _reflection.GeneratedProtocolMessageType('CreateTasksRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATETASKSREQUEST,
  '__module__' : 'flwr.proto.driver_pb2'
  # @@protoc_insertion_point(class_scope:flwr.proto.CreateTasksRequest)
  })
_sym_db.RegisterMessage(CreateTasksRequest)

CreateTasksResponse = _reflection.GeneratedProtocolMessageType('CreateTasksResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATETASKSRESPONSE,
  '__module__' : 'flwr.proto.driver_pb2'
  # @@protoc_insertion_point(class_scope:flwr.proto.CreateTasksResponse)
  })
_sym_db.RegisterMessage(CreateTasksResponse)

GetResultsRequest = _reflection.GeneratedProtocolMessageType('GetResultsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETRESULTSREQUEST,
  '__module__' : 'flwr.proto.driver_pb2'
  # @@protoc_insertion_point(class_scope:flwr.proto.GetResultsRequest)
  })
_sym_db.RegisterMessage(GetResultsRequest)

GetResultsResponse = _reflection.GeneratedProtocolMessageType('GetResultsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETRESULTSRESPONSE,
  '__module__' : 'flwr.proto.driver_pb2'
  # @@protoc_insertion_point(class_scope:flwr.proto.GetResultsResponse)
  })
_sym_db.RegisterMessage(GetResultsResponse)

_DRIVER = DESCRIPTOR.services_by_name['Driver']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETCLIENTSREQUEST._serialized_start=62
  _GETCLIENTSREQUEST._serialized_end=81
  _GETCLIENTSRESPONSE._serialized_start=83
  _GETCLIENTSRESPONSE._serialized_end=103
  _CREATETASKSREQUEST._serialized_start=105
  _CREATETASKSREQUEST._serialized_end=157
  _CREATETASKSRESPONSE._serialized_start=159
  _CREATETASKSRESPONSE._serialized_end=198
  _GETRESULTSREQUEST._serialized_start=200
  _GETRESULTSREQUEST._serialized_end=257
  _GETRESULTSRESPONSE._serialized_start=259
  _GETRESULTSRESPONSE._serialized_end=316
  _DRIVER._serialized_start=319
  _DRIVER._serialized_end=567
# @@protoc_insertion_point(module_scope)
