# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flwr/proto/fleet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from flwr.proto import task_pb2 as flwr_dot_proto_dot_task__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x66lwr/proto/fleet.proto\x12\nflwr.proto\x1a\x15\x66lwr/proto/task.proto\"\x11\n\x0fGetTasksRequest\"2\n\x10GetTasksResponse\x12\x1e\n\x04task\x18\x01 \x03(\x0b\x32\x10.flwr.proto.Task\";\n\x14\x43reateResultsRequest\x12#\n\x07results\x18\x01 \x03(\x0b\x32\x12.flwr.proto.Result\"\x17\n\x15\x43reateResultsResponse2\xa8\x01\n\x05\x46leet\x12G\n\x08GetTasks\x12\x1b.flwr.proto.GetTasksRequest\x1a\x1c.flwr.proto.GetTasksResponse\"\x00\x12V\n\rCreateResults\x12 .flwr.proto.CreateResultsRequest\x1a!.flwr.proto.CreateResultsResponse\"\x00\x62\x06proto3')



_GETTASKSREQUEST = DESCRIPTOR.message_types_by_name['GetTasksRequest']
_GETTASKSRESPONSE = DESCRIPTOR.message_types_by_name['GetTasksResponse']
_CREATERESULTSREQUEST = DESCRIPTOR.message_types_by_name['CreateResultsRequest']
_CREATERESULTSRESPONSE = DESCRIPTOR.message_types_by_name['CreateResultsResponse']
GetTasksRequest = _reflection.GeneratedProtocolMessageType('GetTasksRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTASKSREQUEST,
  '__module__' : 'flwr.proto.fleet_pb2'
  # @@protoc_insertion_point(class_scope:flwr.proto.GetTasksRequest)
  })
_sym_db.RegisterMessage(GetTasksRequest)

GetTasksResponse = _reflection.GeneratedProtocolMessageType('GetTasksResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETTASKSRESPONSE,
  '__module__' : 'flwr.proto.fleet_pb2'
  # @@protoc_insertion_point(class_scope:flwr.proto.GetTasksResponse)
  })
_sym_db.RegisterMessage(GetTasksResponse)

CreateResultsRequest = _reflection.GeneratedProtocolMessageType('CreateResultsRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATERESULTSREQUEST,
  '__module__' : 'flwr.proto.fleet_pb2'
  # @@protoc_insertion_point(class_scope:flwr.proto.CreateResultsRequest)
  })
_sym_db.RegisterMessage(CreateResultsRequest)

CreateResultsResponse = _reflection.GeneratedProtocolMessageType('CreateResultsResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATERESULTSRESPONSE,
  '__module__' : 'flwr.proto.fleet_pb2'
  # @@protoc_insertion_point(class_scope:flwr.proto.CreateResultsResponse)
  })
_sym_db.RegisterMessage(CreateResultsResponse)

_FLEET = DESCRIPTOR.services_by_name['Fleet']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETTASKSREQUEST._serialized_start=61
  _GETTASKSREQUEST._serialized_end=78
  _GETTASKSRESPONSE._serialized_start=80
  _GETTASKSRESPONSE._serialized_end=130
  _CREATERESULTSREQUEST._serialized_start=132
  _CREATERESULTSREQUEST._serialized_end=191
  _CREATERESULTSRESPONSE._serialized_start=193
  _CREATERESULTSRESPONSE._serialized_end=216
  _FLEET._serialized_start=219
  _FLEET._serialized_end=387
# @@protoc_insertion_point(module_scope)
